INSERT INTO users (name, birthday, email, password, bio, profile_picture, created_at, updated_at)
VALUES 
('Andrei Stefan', '2003-02-12', 'stefan.andrei@example.com', 'password123', 'I am not lazy, I am just in energy-saving mode.', null, NOW(), NOW()),
('Will Smith', '1968-09-25', 'will.smith@example.com', 'password123', 'I am not a prince, I am a king!', null, NOW(), NOW()),
('Barbulescu Robert', '2002-07-24', 'barbulescu.robert@example.com', 'password123', 'I am not arguing, I am just passionately expressing my opinion.', null, NOW(), NOW()),
('Andrei Cristian', '1986-11-12', 'cristian.andrei@example.com', 'password123', 'I am not short, I am just concentrated awesome.', null, NOW(), NOW()),
('Bors Andrei', '2001-01-01', 'fraier.bors.andrei@example.com', 'password123', 'I am not a morning person, I am a coffee person.', null, NOW(), NOW()),
('Loser Davis', '2002-02-02', 'loser.davis@example.com', 'password123', 'I am not lazy, I am just on my energy-saving mode!', null, NOW(), NOW()),
('Thomas Edison', '2003-03-03', 'edison.thomas@example.com', 'password123', 'I am not a failure, I am just a work in progress.', null, NOW(), NOW()),
('Elon Musk', '2004-04-04', 'not.loved.by.father@example.com', 'password123', 'I am not a billionaire, I am just a visionary.', null, NOW(), NOW()),
('George Walker Bush', '2005-05-05', 'president123@example.com', 'password123', 'I am not a politician, I am just a public servant.', null, NOW(), NOW()),
('Bruce Wayne', '2006-06-06', 'not.batman@example.com', 'password123', 'I am not Batman, I am just his alter ego.', null, NOW(), NOW()),
('Christian Bale', '2007-07-07', 'sigma@example.com', 'password123', 'I am not an actor, I am just playing one on TV.', null, NOW(), NOW()),
('Adam West', '2008-08-08', 'east.adam@example.com', 'password123', 'I am not old, I am just retro.', null, NOW(), NOW()),
('Tom Holland', '2009-09-09', 'not.spiderman2@example.com', 'password123', 'I am not Spiderman, I am just his friendly neighborhood actor.', null, NOW(), NOW()),
('Andrew Garfield', '2010-10-10', 'not.spiderman1@example.com', 'password123', 'I am not Tobey Maguire, I am just another Spiderman actor.', null, NOW(), NOW()),
('Tobey Maguire', '2011-11-11', 'not.spiderman@example.com', 'password123', 'I am not the original Spiderman, I am just his predecessor.', null, NOW(), NOW()),
('Andrei Stefan Alexandru', '2012-12-12', 'stefan-alexandru.andrei@example.com', 'password123', '🤪😂 Just a kid living his best life!', null, NOW(), NOW()),
('Dwayne Johnson', '1972-05-02', 'hard.as.a.rock@example.com', 'password123', '💪🏽😎 Can you smell what The Rock is cooking?', null, NOW(), NOW()),
('Relu Colonelu', '2002-07-24', 'colonelu4@example.com', 'password123', '🕵️‍♂️🕵️‍♂️ Hey, I am Bob Johnson, or am I? 🤔', null, NOW(), NOW()),
('Andrew Tate', '1986-12-01', 'white.wife.beater@example.com', 'password123', '🥊😉 Dont mess with me, I am a kickboxing world champion!', null, NOW(), NOW()),
('Bors Marius', '2001-01-02', 'cum.sa.te.cheme.Bob.Marius@example.com', 'password123', '👋🏼😃 Greetings, I am David Lee, but you can call me Bob!', null, NOW(), NOW()),
('Michael De Santa', '1965-01-12', 'not.fictional@example.com', 'password123', '👨‍👦🌳 Just a regular guy with a not-so-regular life!', null, NOW(), NOW()),
('Timmy Turner', '1992-03-21', 'fifty.years.old@example.com', 'password123', '🤪😜 Hello there, I am Tom Wilson, forever young at heart!', null, NOW(), NOW()),
('IS 12 ASA', '2021-12-05', 'hotie@example.com', 'password123', '👶🏼🍼 Just a baby exploring the world!', null, NOW(), NOW()),
('Numarul De Mai Sus Este Furat', '2021-12-06', 'hotie1@example.com', 'password123', '🕵️‍♀️🔎 Detective by day, hacker by night!', null, NOW(), NOW()),
('Trebuia Sa Fie Al Meu', '2021-12-07', 'hotie2@example.com', 'password123', '😜😂 Life is too short to be serious all the time!', null, NOW(), NOW()),
('IS 21 ASA', '2021-12-08', 'hotie3@example.com', 'password123', '🎓📚 Just a student trying to figure it all out!', null, NOW(), NOW()),
('Aurora Elvira', '2001-05-14', 'nu.stiu.cine.e.asta@example.com', 'password123', '🤷‍♀️🤷‍♂️ Just two people trying to figure out who Aurora Elvira is...', null, NOW(), NOW()),
('Unlucky 2G', '1984-03-03', 'trick.forty.year.old@example.com', 'password123', '🎂👴🏼 Getting older but not necessarily wiser!', null, NOW(), NOW()),
('Tyler Two', '1995-03-07', 'tyler.one.wannabe@example.com', 'password123', 'I can beat Tyler1 whenever I want to!', null, NOW(), NOW()),
('Adin Not Ross', '2000-11-11', 'little.topG@example.com', 'password123', 'Bald and girlfriendless.', null, NOW(), NOW());