services:
  database:
    container_name: mysql-facebook-build
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/db-config/passFile
    volumes:
      - ../database/config/:/db-config
      - C:\docker-data\mysql-facebook:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    expose:
      - "3306"
  build-env:
    container_name: build-env
    image: build-env-image
    command: ["sleep", "infinity"]
    volumes:
      - ../Facebook/:/Facebook/
    depends_on:
      - database
    