services:
  database:
    container_name: mysql-facebook
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/db-config/passFile
    volumes:
      - .:/db-config
      - C:\docker-data\mysql-facebook:/var/lib/mysql
    ports:
      - "3300:3306"
    expose:
      - "3306"
    network_mode: bridge
#  facebook-core:
#    container_name: facebook-core
#    image: